name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, openssl, curl, xdebug

      - name: Validate composer.json
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run phpstan (optional)
        run: |
          if [ -f phpstan.neon ] || [ -f phpstan.neon.dist ]; then
            vendor/bin/phpstan analyse -l 7 -c phpstan.neon || true
          else
            echo "phpstan config not found, skipping"
          fi

      - name: Run tests (phpunit + coverage)
        run: |
          if [ -f phpunit.xml ] || [ -f phpunit.xml.dist ]; then
            echo "Running phpunit and generating coverage.xml"
            vendor/bin/phpunit --colors=always --coverage-clover=coverage.xml || true
          else
            echo "phpunit config not found, skipping"
          fi

      - name: Show workspace files (debug)
        run: |
          echo "CWD: $(pwd)"
          ls -la
          if [ -f coverage.xml ]; then echo "coverage.xml found"; else echo "coverage.xml NOT found"; fi
 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          verbose: true
          fail_ci_if_error: false
